version: '3.8'

networks:
  inception:
    name: inception
    driver: bridge

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - MYSQL_USER=$ADMIN_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    container_name: nginx
    restart: on-failure
    networks:
      - inception
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile 
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      o: bind
      device: /home/cllovio/data/wordpress
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      o: bind
      device: /home/cllovio/data/mariadb