version: '3.8'

networks :
  inception:
    name: inception
    driver: bridge

services :
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    env_file:
      - .env
    volumes:
      - ./requirements/mariadb:/var/lib/mysql:rw
    restart: on-failure
    ports:
      - 3306:3306

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    build:
        context: requirements/nginx
        dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - "443:443"
    # volume:
    #   - ./requirements/nginx/conf/nginx.conf:etc/nginxconf.d/core.conf
    # links:
    #   - mariadb


# volume:
#   maridb:

# network:
#   inception